c_compiler:
  - gcc                        # [linux]
  - clang                      # [osx]
  - gcc           # [win]
cxx_compiler:
  - gxx                        # [linux]
  - clangxx                    # [osx]
  - gxx      # [win]