c_compiler:
  - mingw32  # [win]
cxx_compiler:
  - mingw32  # [win]
# Ignore any Visual Studio pins
vc:
  - none
vs2017_runtime:
  - none
vs2019_runtime:
  - none
vs2022_runtime:
  - none

# Optionally ignore pins from conda-forge
ignore_pins:
  - vc
  - vs2017
  - vs2019
  - vs2022