c_compiler:
  - gcc                        # [linux]
  - clang                      # [osx]
  - gcc                     # [win]
c_compiler_version:            # [unix]
  - 14                         # [linux]
  - 19                         # [osx]
  # CUDA 12.6 doesn't support GCC 14
  - 13                         # [linux and not ppc64le and os.environ.get("CF_CUDA_ENABLED", "False") == "True"]
c_stdlib:
  - sysroot                    # [linux]
  - macosx_deployment_target   # [osx]
  - m2w64-sysroot                         # [win]
m2w64_c_stdlib:                # [win]
  - m2w64-sysroot              # [win]
m2w64_c_stdlib_version:        # [win]
  - 12                         # [win]
c_stdlib_version:              # [unix]
  - 2.17                       # [linux]
  - 2.17                       # [linux and not ppc64le and os.environ.get("CF_CUDA_ENABLED", "False") == "True"]
  - 10.13                      # [osx and x86_64]
  - 11.0                       # [osx and arm64]
cxx_compiler:
  - gxx                        # [linux]
  - clangxx                    # [osx]
  - gxx                     # [win]
cxx_compiler_version:          # [unix]
  - 14                         # [linux]
  - 19                         # [osx]
  - 13                         # [linux and not ppc64le and os.environ.get("CF_CUDA_ENABLED", "False") == "True"]
llvm_openmp:                   # [osx]
  - 19                         # [osx]
fortran_compiler:              # [unix or win64]
  - gfortran                   # [linux64 or (osx and x86_64)]
  - gfortran                   # [aarch64 or ppc64le or armv7l or s390x]
  - flang                      # [win64]
fortran_compiler_version:      # [unix or win64]
  - 14                         # [linux]
  - 14                         # [osx]
  - 5                          # [win64]
  - 13                         # [linux and not ppc64le and os.environ.get("CF_CUDA_ENABLED", "False") == "True"]
m2w64_c_compiler:                 # [win]
  - gcc                           # [win]
m2w64_c_compiler_version:         # [win]
  - 14                            # [win]
m2w64_cxx_compiler:               # [win]
  - gxx                           # [win]
m2w64_cxx_compiler_version:       # [win]
  - 14                            # [win]
m2w64_fortran_compiler:           # [win]
  - gfortran                      # [win]
m2w64_fortran_compiler_version:   # [win]
  - 14                            # [win]
