channels:
  - openalea3/label/dev
  - openalea3/label/rc
  - openalea3
  - conda-forge
dependencies:
  - python
  - openalea.libcaribu
  - openalea.plantgl
  - openalea.widgets
  - pip
  - pip:
      - -e ..[doc,test]