{% set pyproject = load_file_data('pyproject.toml') %}
{% set description = pyproject.get('project', {}).get('description') %}
{% set home = pyproject.get('project', {}).get('urls').get('Homepage') %}

{# Align version with the one computed by setuptools_scm #}
{% set base_tag = GIT_DESCRIBE_TAG | default("0.0.0.dev0") | replace("v", "") %}
{% set distance = GIT_DESCRIBE_NUMBER | default("0") | int %}
{% set base_parts = base_tag.split('.') %}
{% set micro = base_parts[2] | int %}
{% set next_version = base_parts[0] + "." + base_parts[1] + "." + (micro + 1)|string %}
{% set scm_version = next_version + ".dev" + distance|string if distance > 0 else base_tag %}
{% set version = environ.get('SETUPTOOLS_SCM_PRETEND_VERSION', scm_version) %}

package:
  name: alinea.caribu
  version: {{ version }}

source:
  path: ..

build:
  string: py{{ PY_VER }}
  script_env:
    - CMAKE_GEN=MinGW Makefiles # [win]
    - CMAKE_GENERATOR=MinGW Makefiles # [win]
  script:
    - {{PYTHON}} -m pip install --no-deps --prefix={{ PREFIX }} . -vv

requirements:
  host:
    - python
    - pip
    - scikit-build-core
    - setuptools
    - wheel
    - cmake
    - make              # [unix]
    - ninja
  build:
    - {{ compiler('c') }}   
    - {{ compiler('cxx') }}
    - m2w64-toolchain   # [win]
  run:
    - python
    - path              # path.py is outdated
    - openalea.plantgl
    - openalea.mtg

test:
  requires:
    - pytest
  imports:
    - alinea.caribu
  source_files:
    - test/*.py
  commands:
   - pytest -v

about:
  home: {{ home }}
  description: {{ description }}
  summary: {{ description }}
  license: CeCILL_C