name: caribu
channels:
  - openalea3/label/dev
  - openalea3/label/rc
  - conda-forge

dependencies:
  - openalea.caribu
  - oawidgets
  - pip
  - pip:
    - pydata-sphinx-theme
    - myst-parser
    - sphinx-favicon
    - nbsphinx
