name: OpenAlea CI

on:
  push:
    branches:
      - main
      - master
    tags:
      - 'v*'
  pull_request:
    types:
      - opened
      - synchronize
      - reopened
  release:
    types:
      - published

jobs:
  build:
    uses: openalea/action-build-publish-anaconda/.github/workflows/openalea_ci.yml@use_dev
    secrets:
      anaconda_token: ${{ secrets.ANACONDA_TOKEN }}
  